package main

import (
	"fiber-boilerplate/config"
	"fiber-boilerplate/controller"
	"fiber-boilerplate/exception"
	"fiber-boilerplate/migrations"
	"fiber-boilerplate/repository"
	"fiber-boilerplate/router"
	"fiber-boilerplate/service"
	"log"

	_ "fiber-boilerplate/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/go-playground/validator/v10"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	"github.com/swaggo/fiber-swagger"
)

// @title Boilerplate Api
// @version 1.0
// @description Boilerplate API in Go using Fiber framework

// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

// @host localhost:3000
// @BasePath /api/v1
func main() {
	loadConfig, err := config.LoadConfig(".")
	if err != nil {
		log.Fatal("🚀 Could not load environment variables", err)
	}

	//Database
	db := config.ConnectionDB(&loadConfig)
	validate := validator.New()

	migrations.AutoMigrate(db)

	// init repository
	noteRepository := repository.NewNoteRepositoryImpl(db)

	// init service
	noteService := service.NewNoteServiceImpl(noteRepository, validate)

	// init controller
	noteController := controller.NewNoteController(noteService)

	routes := router.NewRouter(noteController)

	app := fiber.New(fiber.Config{
		ErrorHandler: exception.ErrorHandler,
	})
	app.Use(recover.New())
	app.Use(requestid.New())
	app.Use(logger.New(logger.Config{
		Format: "[${locals:requestid}] ${ip} - ${method} ${status} ${path} - ${latency}\n",
	}))

	app.Mount("/api/v1", routes)
	app.Get("/swagger/*", fiberSwagger.WrapHandler)
	log.Fatal(app.Listen(":" + loadConfig.ServerPort))
}
